spring.application.name=SecurityApplication
spring.datasource.url=jdbc:mysql://localhost:3306/security-app?useSSL=false
spring.datasource.username=root
spring.datasource.password=Pratik@21
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

employeeService.base.url = http://127.0.0.1:8080/audit/

#Spring Security

#spring.security.user.name=pratik
#spring.security.user.password=pass

jwt.secretKey=dasdjfnsdsmwreeuewrnvdms13123edsar123rfscse1228eujcnrtir7uefnvr4iu44reg

deploy.env=development